# This file was generated by GoReleaser. DO NOT EDIT.
cask "es-tui" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "6c62bd20bf0ddfb4e6462adfff211ecf8a16081d3656749d92728c9b5c6cb134"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d408627745b60f1a8d58d9a5afcd70fb8943d6bdb00b56b386fe3a64ee3f7b76"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f78073b05fffbb82ce0b9587745736de8c4743803fbf762d9af4637aae8852e5"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8ca9dd39780c97d7dc2ccbb6e34799e6973f32c26433fa916f0b682d8a267d8b"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "es-tui"
  desc "Lightweight Elasticsearch / OpenSearch TUI Manager"
  homepage "https://github.com/davidbudnick/es-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "es-tui"

  # No zap stanza required

end
