# This file was generated by GoReleaser. DO NOT EDIT.
cask "es-tui" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "eb098ce4e565573ee7f89acbe9c5b16c4610801a799b67bc2fdf1806b8f63f9c"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f8457ebc07d2e851582c5d68ca0e33e9f272ef56be36941e3bc9c6a63bdd7f4e"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e2a5e0cd206996d340240461c6fabebaeadb79655d4209fdce16fa0836d679e"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a9678a7598bd6d911a6f1e177727d27514c0b6ac0964b1b80a4529f72ab106e4"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "es-tui"
  desc "Lightweight Elasticsearch / OpenSearch TUI Manager"
  homepage "https://github.com/davidbudnick/es-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "es-tui"

  # No zap stanza required

end
