# This file was generated by GoReleaser. DO NOT EDIT.
cask "es-tui" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "b3d0469023c92fbb62dd195b8a62c27d1dd5413838c8d258ba810a5408610d3c"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7f9bb870a8695b9f34ce445f50dd0bbd5a34a74da9d41dda59b9c4433846b1a0"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4cbeb8ae885af4d6953dea10a55270b4364e95967a6e1cbda1de8b41c4da5e52"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d58519377758c4f8fd386a9806603fb0a4a3df51f77875243d3e7f95be4638f7"
      url "https://github.com/davidbudnick/es-tui/releases/download/v#{version}/es-tui_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "es-tui"
  desc "Lightweight Elasticsearch / OpenSearch TUI Manager"
  homepage "https://github.com/davidbudnick/es-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "es-tui"

  # No zap stanza required

end
