# This file was generated by GoReleaser. DO NOT EDIT.
cask "postgres-tui" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "28a0a5a9a842e4bf9a0a10c45b5beca2e54a3bedc93b600dd8d8621f179f8a1c"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e6bee04f8c6fddccf920b7bc163ba911959585c27f0b0a075d77dc724c0b254f"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d5a596e95c4848fb29399256d9d932cda4543dcae622c4a562f884258280642"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d12a716820607156447556c72f34eece621b686f9809cf28db3992ab477a2982"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "postgres-tui"
  desc "Lightweight PostgreSQL TUI Manager"
  homepage "https://github.com/davidbudnick/postgres-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "postgres-tui"

  # No zap stanza required

end
