# This file was generated by GoReleaser. DO NOT EDIT.
cask "postgres-tui" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "1546e4925da29ce5406b3495d4cfa820e0e0c4b6073af4523032d703c75e6d35"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "52de19d8f8e0fe27951595aa274514493c1242046a8442e2997949a18131f780"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f38430358acd027fe556dc046e363b269bb54c7d9b65f117d81f43125b96fc5"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "622b3fee82065faf99e5a3c62aef2e472a59057e0a5a067c6c2a2eaf7e3c5e2b"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "postgres-tui"
  desc "Lightweight PostgreSQL TUI Manager"
  homepage "https://github.com/davidbudnick/postgres-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "postgres-tui"

  # No zap stanza required

end
