# This file was generated by GoReleaser. DO NOT EDIT.
cask "postgres-tui" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "61b7f7b36a3913c8d1e81343f7a6ab8b1b2dfa395e572a8ffe283e0777a0f117"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a3d34207ca33f2a1aab20907c1fc4b20485d8bf268b3b255a2835eab41f2217c"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "10d1a6f521aab2b4e0b1ba8fee749a25df7f51c0e11d029215000529a3bab720"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fd6d46858deeb5cfc55fb5eb44ef0ebb8a3117ba96af334ce0706aaa10e01b07"
      url "https://github.com/davidbudnick/postgres-tui/releases/download/v#{version}/postgres-tui_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "postgres-tui"
  desc "Lightweight PostgreSQL TUI Manager"
  homepage "https://github.com/davidbudnick/postgres-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "postgres-tui"

  # No zap stanza required

end
