# This file was generated by GoReleaser. DO NOT EDIT.
cask "redis-tui" do
  name "redis-tui"
  desc "A powerful TUI for managing Redis databases"
  homepage "https://github.com/davidbudnick/redis-tui"
  version "1.0.20"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redis-tui"

  on_macos do
    on_intel do
      url "https://github.com/davidbudnick/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Darwin_x86_64.tar.gz"
      sha256 "09ec2400d4d2943320d88344e1844fe941834a130606bca806916774ad3d4cce"
    end
    on_arm do
      url "https://github.com/davidbudnick/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Darwin_arm64.tar.gz"
      sha256 "bbbbfc11661719eab3ca8a40f50a3c21e13d51a973b9e411514484dc034771c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/davidbudnick/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Linux_x86_64.tar.gz"
      sha256 "ef4b99452daa325c788ebeaeb0d35f4b598dc8a538469a76ce9f1a90ddfb096a"
    end
    on_arm do
      url "https://github.com/davidbudnick/redis-tui/releases/download/v#{version}/redis-tui_#{version}_Linux_arm64.tar.gz"
      sha256 "4751e5c227b9bba4a55bfb4fca33a3aff98719eafd9d237121897ab38e990a31"
    end
  end

  # No zap stanza required
end
