# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisTui < Formula
  desc "A powerful TUI for managing Redis databases"
  homepage "https://github.com/davidbudnick/redis"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.4/redis-tui_1.0.4_Darwin_x86_64.tar.gz"
      sha256 "39dc96560c19207ea9d788745d4721c5e104fcf4d30eca5a222108e9a783c1c1"

      def install
        bin.install "redis-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.4/redis-tui_1.0.4_Darwin_arm64.tar.gz"
      sha256 "5c096f243634a90165ae81afc092a989c96de2896496812a41a6e3d5b9008965"

      def install
        bin.install "redis-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.4/redis-tui_1.0.4_Linux_x86_64.tar.gz"
      sha256 "9cb29d143c9ae3a4b7809fca5dd6bcc89f6637a37fee4f1836714a4dff005790"
      def install
        bin.install "redis-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.4/redis-tui_1.0.4_Linux_arm64.tar.gz"
      sha256 "1b1be55bace95a0be8d1b495d4d6bdf9de913af7e9d8234cd6fe98fc14d36bbf"
      def install
        bin.install "redis-tui"
      end
    end
  end
end
