# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisTui < Formula
  desc "A powerful TUI for managing Redis databases"
  homepage "https://github.com/davidbudnick/redis"
  version "1.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.9/redis-tui_1.0.9_Darwin_x86_64.tar.gz"
      sha256 "ae234ed5c6f73848b22b75b0ec6e5fe79e44f2ab951f091f04441f5ca7ae0dc6"

      def install
        bin.install "redis-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.9/redis-tui_1.0.9_Darwin_arm64.tar.gz"
      sha256 "545ce12ebb914c1bd664716acf8556b114a546aae11db5111c756ddd6598aeca"

      def install
        bin.install "redis-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.9/redis-tui_1.0.9_Linux_x86_64.tar.gz"
      sha256 "e018c1ca82b0c3e86d0442af8f9aef077061f59e75bc1792bf5c88b1dd9e52c0"
      def install
        bin.install "redis-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.9/redis-tui_1.0.9_Linux_arm64.tar.gz"
      sha256 "80f3519dc5778d69eedc62043c80380b4bca4158580e6e25f3fc0d2a9627e7cd"
      def install
        bin.install "redis-tui"
      end
    end
  end
end
