# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedisTui < Formula
  desc "A powerful TUI for managing Redis databases"
  homepage "https://github.com/davidbudnick/redis"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.3/redis-tui_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "9f534bc77676253e532e76a8a4b5123ae8f1e93d136e6409b6fbaaea710c7133"

      def install
        bin.install "redis-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.3/redis-tui_1.0.3_Darwin_arm64.tar.gz"
      sha256 "adf545e0fdbe09beaeddb3d7bc13c653d04f5b005e09e580e503107924ff0c70"

      def install
        bin.install "redis-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.3/redis-tui_1.0.3_Linux_x86_64.tar.gz"
      sha256 "85a7d8a034c757ef275086d2e976f6f45078ca33cb61e6031abbbe5aeb72f51c"
      def install
        bin.install "redis-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/davidbudnick/redis/releases/download/v1.0.3/redis-tui_1.0.3_Linux_arm64.tar.gz"
      sha256 "e59cbeae43460449a8f163addfea1d2662c3f5318d410d3dba0a52311ba37f37"
      def install
        bin.install "redis-tui"
      end
    end
  end
end
